### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by adhu2018** [zsakvo/YueDuCacheHelper#2]
新版扫描不到文件，用v1.1.0209 就可以，机型VIVOY66 Android6.0.1

**Comment by ghost** [comment]
等了半天没扫描到书，位置没变，书也缓存了

**Comment by zsakvo** [comment]
新版阅读相关参数有所改变，最近要预备春招事宜，较为忙碌，下周会尽量释出新版本，望理解……

**Comment by adhu2018** [comment]
感谢开发者百忙之中回答我的问题，还有的就是，之前我已经尝试过改变缓存位置，但还是没有扫描出来。
