### ISSUE TITLE
能提供导出mobi格式的功能吗？

### ISSUE THREAD

**Issue by hjianhao** [zsakvo/YueDuCacheHelper#3]
能导出mobi就可以直接在kindle上看了，也可以利用kindle的功能。azw3格式也行。

kindle不支持epub，txt格式不支持目录提取。

**Comment by zsakvo** [comment]
有考虑过，会慢慢加上

**Comment by kerncoola** [comment]
epub也行，哪个实现方便搞哪个...

**Comment by kerncoola** [comment]
支持。

**Comment by zsakvo** [comment]
看了一下，后续大概会做一个电脑端的提取软件来解决这个问题，直接在 Android 上生成 mobi 并没有什么很好的办法……
