### ISSUE TITLE
导出的epub章节名和正文一样，章节名后无换行，直接跟着正文。

### ISSUE THREAD

**Issue by kerncoola** [zsakvo/YueDuCacheHelper#5]
建议章节名比正文大一号，不然看起来不舒服，希望大佬修复一下，用的是iBooks阅读。

**Comment by kerncoola** [comment]
如图。

**Comment by kerncoola** [comment]
![image](https://user-images.githubusercontent.com/13283995/58398713-7f3b2180-8088-11e9-9ea3-809b8bcdc527.png)

**Comment by zsakvo** [comment]
嗯 知道了，新版重写的时候会注意
